package stacks

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"strconv"
	"strings"
)

// BaseImage is the image every generated Dockerfile starts from.
const BaseImage = "ubuntu:24.04"

// Paths of the generated files inside the build context.
const (
	ContextDockerfile      = "Dockerfile"
	ContextStacks          = "aide/stacks"
	ContextCacheDirs       = "aide/cache-dirs"
	ContextHooksDir        = "aide/entrypoint.d"
	ContextManagedSettings = "aide/managed-settings.json"
	ContextOpencode        = "aide/opencode.json"
)

// Stacks whose presence turns on the policy files.
const (
	ClaudeStack = "claude"
)

// OpencodeStacks are the stacks that install an opencode binary.
var OpencodeStacks = []string{"opencode", "opencode-filesystem"}

// HasOpencode reports whether any opencode stack is in the resolution.
func (r *Resolution) HasOpencode() bool {
	for _, n := range OpencodeStacks {
		if r.Has(n) {
			return true
		}
	}
	return false
}

// StackFilePath is the context path of a stack's files/<rel>; fragments COPY from it.
func StackFilePath(stack, rel string) string { return path.Join("stacks", stack, "files", rel) }

// Generate renders the Dockerfile and assembles the build context.
func Generate(r *Resolution) (*BuildContext, error) {
	files := map[string]File{}
	hookOwner := map[string]string{}
	var cache []string
	var claudeDocs, opencodeDocs [][]byte

	for _, s := range r.Stacks {
		if err := ValidateStack(s); err != nil {
			return nil, err
		}
		for _, rel := range sortedKeys(s.Files) {
			f := s.Files[rel]
			if f.Mode.Perm() == 0 {
				f.Mode = fileMode(rel)
			}
			files[StackFilePath(s.Name, rel)] = File{Data: f.Data, Mode: f.Mode.Perm()}
		}
		for _, h := range sortedKeys(s.Hooks) {
			if other, ok := hookOwner[h]; ok {
				return nil, fmt.Errorf("hook entrypoint.d/%s is provided by both %s and %s", h, other, s.Name)
			}
			hookOwner[h] = s.Name
			files[path.Join(ContextHooksDir, h)] = File{Data: s.Hooks[h].Data, Mode: 0o755}
		}
		cache = append(cache, s.Cache...)
		if d, ok := s.Contrib[ContribClaude]; ok {
			claudeDocs = append(claudeDocs, d)
		}
		if d, ok := s.Contrib[ContribOpencode]; ok {
			opencodeDocs = append(opencodeDocs, d)
		}
	}

	names := r.Names()
	files[ContextStacks] = File{Data: []byte(lines(names)), Mode: 0o644}
	files[ContextCacheDirs] = File{Data: []byte(lines(sortDedup(cache))), Mode: 0o644}

	claude := r.Has(ClaudeStack)
	if claude {
		m, err := MergeJSON(claudeDocs...)
		if err != nil {
			return nil, fmt.Errorf("merging contrib/%s: %w", ContribClaude, err)
		}
		files[ContextManagedSettings] = File{Data: m, Mode: 0o644}
	}
	opencode := r.HasOpencode()
	if opencode {
		m, err := MergeJSON(opencodeDocs...)
		if err != nil {
			return nil, fmt.Errorf("merging contrib/%s: %w", ContribOpencode, err)
		}
		files[ContextOpencode] = File{Data: m, Mode: 0o644}
	}

	var b strings.Builder
	w := func(format string, a ...any) { fmt.Fprintf(&b, format+"\n", a...) }
	joined := strings.Join(names, " ")
	w("# syntax=docker/dockerfile:1")
	w("# Generated by aide. Stacks: %s", joined)
	w("FROM %s", BaseImage)
	w("ARG TARGETARCH")
	w("ENV DEBIAN_FRONTEND=noninteractive LANG=C.UTF-8")
	for _, s := range r.Stacks {
		w("")
		w("# ---- stack: %s ----", s.Name)
		if frag := strings.TrimRight(s.Fragment, "\n\r\t "); frag != "" {
			w("%s", frag)
		}
		w("USER root")
	}
	w("")
	w("# ---- aide common tail ----")
	w(`RUN if [ -d /opt/node ]; then v=$(ls /opt/node | grep -E '^[0-9]+$' | sort -n | tail -1); [ -n "$v" ] && ln -sfn /opt/node/$v /opt/node/current; fi`)
	if claude {
		// COPY --chmod also applies the mode to a parent directory it creates,
		// which would leave /etc/claude-code without the execute bit and the
		// policy unreadable by the agent user.
		w("RUN install -d -m 0755 /etc/claude-code")
		w("COPY --chmod=0644 %s /etc/claude-code/managed-settings.json", ContextManagedSettings)
	}
	if opencode {
		w("COPY --chown=agent:agent %s %s/.config/opencode/opencode.json", ContextOpencode, AgentHome)
	}
	w("COPY %s %s %s/", ContextStacks, ContextCacheDirs, EtcDir)
	if len(hookOwner) > 0 {
		w("COPY --chmod=0755 %s/ %s/entrypoint.d/", ContextHooksDir, EtcDir)
	}
	w("ENV AIDE_STACKS=%s WORKSPACE=%s CODE_SERVER_PORT=%d", strconv.Quote(joined), WorkspaceDir, CodeServerPort)
	w("USER root")
	w("WORKDIR %s", WorkspaceDir)
	w("EXPOSE %d", CodeServerPort)
	w(`ENTRYPOINT ["%s/entrypoint.sh"]`, EtcDir)

	bc := &BuildContext{Dockerfile: []byte(b.String()), Files: files}
	bc.Fingerprint = bc.fingerprint()
	return bc, nil
}

func lines(items []string) string {
	var b strings.Builder
	for _, s := range items {
		b.WriteString(s)
		b.WriteByte('\n')
	}
	return b.String()
}

// Entries returns every file of the context, the Dockerfile included, keyed
// by context path.
func (bc *BuildContext) Entries() map[string]File {
	all := make(map[string]File, len(bc.Files)+1)
	for p, f := range bc.Files {
		all[p] = f
	}
	all[ContextDockerfile] = File{Data: bc.Dockerfile, Mode: 0o644}
	return all
}

// fingerprint hashes, for each entry in path order, the path, the permission
// bits in octal and the data length, each NUL-terminated, followed by the data.
func (bc *BuildContext) fingerprint() string {
	all := bc.Entries()
	h := sha256.New()
	for _, p := range sortedKeys(all) {
		f := all[p]
		fmt.Fprintf(h, "%s\x00%o\x00%d\x00", p, f.Mode.Perm(), len(f.Data))
		h.Write(f.Data)
	}
	return "sha256:" + hex.EncodeToString(h.Sum(nil))
}

// WriteDir writes the build context into dir (which must exist and be empty).
func (bc *BuildContext) WriteDir(dir string) error {
	ents, err := os.ReadDir(dir)
	if err != nil {
		return err
	}
	if len(ents) > 0 {
		return fmt.Errorf("build context directory %s is not empty", dir)
	}
	all := bc.Entries()
	for _, p := range sortedKeys(all) {
		f := all[p]
		if !fs.ValidPath(p) {
			return fmt.Errorf("invalid build context path %q", p)
		}
		dst := filepath.Join(dir, filepath.FromSlash(p))
		if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
			return err
		}
		mode := f.Mode.Perm()
		if mode == 0 {
			mode = 0o644
		}
		if err := os.WriteFile(dst, f.Data, mode); err != nil {
			return err
		}
		if err := os.Chmod(dst, mode); err != nil { // undo the umask
			return err
		}
	}
	return nil
}
