package stacks

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func genCatalog() map[string]*Stack {
	return catalogOf(
		mk("base", 0, fragment("RUN echo base\n\n"), file("entrypoint.sh", "#!/bin/sh\n"), file("conf/x.txt", "x"), cache("xdg")),
		mk("terminalfs", 50, requires("base"), hook("50-terminalfs.sh", "true\n"),
			contrib(ContribClaude, `{"permissions": {"allow": ["Read(t)"]}}`),
			contrib(ContribOpencode, `{"permission": {"bash": {"*": "allow"}}}`)),
		mk("claude", 60, requires("base"), hook("10-claude.sh", "true\n"),
			contrib(ContribClaude, `{"$schema": "s", "permissions": {"allow": ["Bash"]}}`), cache("npm", "xdg")),
		mk("opencode", 70, requires("base")),
		mk("opencode-filesystem", 71, requires("terminalfs"), contrib(ContribOpencode, `{"$schema": "o"}`)),
		mk("dup", 90, requires("base"), hook("10-claude.sh", "false\n")),
	)
}

func mustGenerate(t *testing.T, cat map[string]*Stack, sel ...string) *BuildContext {
	t.Helper()
	bc, err := Generate(mustResolve(t, cat, sel...))
	if err != nil {
		t.Fatalf("Generate(%v): %v", sel, err)
	}
	return bc
}

func TestGenerateConditionalCopies(t *testing.T) {
	cat := genCatalog()
	const claudeCopy = "COPY --chmod=0644 aide/managed-settings.json /etc/claude-code/managed-settings.json\n"
	const ocCopy = "COPY --chown=agent:agent aide/opencode.json /home/agent/.config/opencode/opencode.json\n"
	const hookCopy = "COPY --chmod=0755 aide/entrypoint.d/ /etc/aide/entrypoint.d/\n"

	cases := []struct {
		sel               []string
		claude, oc, hooks bool
	}{
		{[]string{"base"}, false, false, false},
		{[]string{"claude"}, true, false, true},
		{[]string{"opencode"}, false, true, false},
		{[]string{"opencode-filesystem"}, false, true, true},
		{[]string{"claude", "opencode-filesystem"}, true, true, true},
	}
	for _, c := range cases {
		bc := mustGenerate(t, cat, c.sel...)
		df := string(bc.Dockerfile)
		for _, chk := range []struct {
			line string
			want bool
			file string
		}{{claudeCopy, c.claude, ContextManagedSettings}, {ocCopy, c.oc, ContextOpencode}, {hookCopy, c.hooks, ""}} {
			if got := strings.Contains(df, chk.line); got != chk.want {
				t.Errorf("%v: line %q present=%v, want %v", c.sel, chk.line, got, chk.want)
			}
			if chk.file != "" {
				if _, got := bc.Files[chk.file]; got != chk.want {
					t.Errorf("%v: file %s present=%v, want %v", c.sel, chk.file, got, chk.want)
				}
			}
		}
	}
}

func TestGenerateContents(t *testing.T) {
	bc := mustGenerate(t, genCatalog(), "claude", "opencode-filesystem")
	df := string(bc.Dockerfile)
	if !strings.HasPrefix(df, "# syntax=docker/dockerfile:1\n# Generated by aide. Stacks: base terminalfs claude opencode-filesystem\nFROM ubuntu:24.04\n") {
		t.Fatalf("bad header:\n%s", df)
	}
	if !strings.Contains(df, "# ---- stack: base ----\nRUN echo base\nUSER root\n") {
		t.Errorf("base section wrong:\n%s", df)
	}
	if !strings.Contains(df, "# ---- stack: opencode-filesystem ----\nUSER root\n") {
		t.Errorf("empty fragment section wrong:\n%s", df)
	}
	if !strings.Contains(df, `ENV AIDE_STACKS="base terminalfs claude opencode-filesystem" WORKSPACE=/home/agent/workspace CODE_SERVER_PORT=8080`+"\n") {
		t.Errorf("ENV line wrong:\n%s", df)
	}
	if !strings.HasSuffix(df, "USER root\nWORKDIR /home/agent/workspace\nEXPOSE 8080\nENTRYPOINT [\"/etc/aide/entrypoint.sh\"]\n") {
		t.Errorf("tail wrong:\n%s", df)
	}

	f := bc.Files
	eq(t, string(f[ContextStacks].Data), "base\nterminalfs\nclaude\nopencode-filesystem\n")
	eq(t, string(f[ContextCacheDirs].Data), "npm\nxdg\n")
	eq(t, f["stacks/base/files/entrypoint.sh"].Mode, os.FileMode(0o755))
	eq(t, f["stacks/base/files/conf/x.txt"].Mode, os.FileMode(0o644))
	eq(t, f["aide/entrypoint.d/50-terminalfs.sh"].Mode, os.FileMode(0o755))
	eq(t, f["aide/entrypoint.d/10-claude.sh"].Mode, os.FileMode(0o755))
	// Merged in resolution order: terminalfs (50) before claude (60).
	eq(t, string(f[ContextManagedSettings].Data), `{
  "permissions": {
    "allow": [
      "Read(t)",
      "Bash"
    ]
  },
  "$schema": "s"
}
`)
	eq(t, string(f[ContextOpencode].Data), "{\n  \"permission\": {\n    \"bash\": {\n      \"*\": \"allow\"\n    }\n  },\n  \"$schema\": \"o\"\n}\n")
	if _, ok := f[ContextDockerfile]; ok {
		t.Error("Files must not contain the Dockerfile")
	}
}

func TestGenerateDuplicateHook(t *testing.T) {
	_, err := Generate(mustResolve(t, genCatalog(), "claude", "dup"))
	errContains(t, err, "hook entrypoint.d/10-claude.sh is provided by both claude and dup")
}

func TestGenerateRejectsFrom(t *testing.T) {
	for _, frag := range []string{"FROM debian\n", "RUN true\n  from alpine AS x\n"} {
		cat := catalogOf(mk("base", 0, fragment(frag)))
		_, err := Generate(mustResolve(t, cat, "base"))
		errContains(t, err, "FROM is not allowed")
	}
	// A continuation line that happens to start with "from" is fine.
	cat := catalogOf(mk("base", 0, fragment("RUN echo \\\n  from here\n")))
	if _, err := Generate(mustResolve(t, cat, "base")); err != nil {
		t.Fatal(err)
	}
}

func TestGenerateRejectsBadHookName(t *testing.T) {
	cat := catalogOf(mk("base", 0, hook("claude.sh", "")))
	_, err := Generate(mustResolve(t, cat, "base"))
	errContains(t, err, "hook names must match")
}

func TestFingerprint(t *testing.T) {
	cat := genCatalog()
	a := mustGenerate(t, cat, "claude")
	b := mustGenerate(t, cat, "claude", "base")
	if !strings.HasPrefix(a.Fingerprint, "sha256:") || len(a.Fingerprint) != len("sha256:")+64 {
		t.Fatalf("bad fingerprint %q", a.Fingerprint)
	}
	eq(t, a.Fingerprint, b.Fingerprint)

	cat["base"].Files["conf/x.txt"] = File{Data: []byte("y"), Mode: 0o644}
	c := mustGenerate(t, cat, "claude")
	if c.Fingerprint == a.Fingerprint {
		t.Error("fingerprint unchanged after a file's data changed")
	}
	cat["base"].Files["conf/x.txt"] = File{Data: []byte("x"), Mode: 0o600}
	d := mustGenerate(t, cat, "claude")
	if d.Fingerprint == a.Fingerprint {
		t.Error("fingerprint unchanged after a file's mode changed")
	}
	cat["base"].Files["conf/x.txt"] = File{Data: []byte("x"), Mode: 0o644}
	eq(t, mustGenerate(t, cat, "claude").Fingerprint, a.Fingerprint)

	cat["base"].Fragment = "RUN echo changed\n"
	if mustGenerate(t, cat, "claude").Fingerprint == a.Fingerprint {
		t.Error("fingerprint unchanged after the Dockerfile changed")
	}
}

func TestWriteDir(t *testing.T) {
	bc := mustGenerate(t, genCatalog(), "claude")
	dir := t.TempDir()
	if err := bc.WriteDir(dir); err != nil {
		t.Fatal(err)
	}
	for p, f := range bc.Entries() {
		fi, err := os.Stat(filepath.Join(dir, filepath.FromSlash(p)))
		if err != nil {
			t.Fatal(err)
		}
		if fi.Mode().Perm() != f.Mode.Perm() {
			t.Errorf("%s: mode %o, want %o", p, fi.Mode().Perm(), f.Mode.Perm())
		}
		data, _ := os.ReadFile(filepath.Join(dir, filepath.FromSlash(p)))
		if string(data) != string(f.Data) {
			t.Errorf("%s: content differs", p)
		}
	}
	err := bc.WriteDir(dir)
	errContains(t, err, "not empty")
}
