# syntax=docker/dockerfile:1
# Generated by aide. Stacks: base
FROM ubuntu:24.04
ARG TARGETARCH
ENV DEBIAN_FRONTEND=noninteractive LANG=C.UTF-8

# ---- stack: base ----
# PLACEHOLDER base stack fragment (stacks engine work package). A later work
# package replaces it with the real base: apt packages, code-server, the agent
# user, lib.sh and install-node.sh.
COPY --chmod=0755 stacks/base/files/entrypoint.sh /etc/aide/entrypoint.sh
RUN echo base
USER root

# ---- aide common tail ----
RUN if [ -d /opt/node ]; then v=$(ls /opt/node | grep -E '^[0-9]+$' | sort -n | tail -1); [ -n "$v" ] && ln -sfn /opt/node/$v /opt/node/current; fi
COPY aide/stacks aide/cache-dirs /etc/aide/
COPY --chmod=0755 aide/entrypoint.d/ /etc/aide/entrypoint.d/
ENV AIDE_STACKS="base" WORKSPACE=/home/agent/workspace CODE_SERVER_PORT=8080
USER root
WORKDIR /home/agent/workspace
EXPOSE 8080
ENTRYPOINT ["/etc/aide/entrypoint.sh"]
