# syntax=docker/dockerfile:1
# Generated by aide. Stacks: base dotnet10 python3 clang golang node24 gh qode terminalfs claude opencode-filesystem dotnetdocfs
FROM ubuntu:24.04
ARG TARGETARCH
ENV DEBIAN_FRONTEND=noninteractive LANG=C.UTF-8

# ---- stack: base ----
# mount/mountpoint (util-linux) mount the 9P filesystems and setpriv drops
# privileges in the entrypoint. tinyproxy and iptables are the network
# allowlist (aide-network.sh), and netcat-openbsd carries ssh through it. ripgrep is used by both agents' search tools;
# without a system rg they each download their own copy on first use. xz-utils
# unpacks the nodejs.org tarballs.
RUN apt-get update && apt-get install -y --no-install-recommends \
        bash \
        build-essential \
        ca-certificates \
        curl \
        file \
        git \
        gnupg \
        gzip \
        htop \
        iptables \
        jq \
        less \
        libsecret-1-0 \
        locales \
        mount \
        nano \
        neovim \
        netcat-openbsd \
        openssh-client \
        pkg-config \
        procps \
        ripgrep \
        rsync \
        sudo \
        tar \
        tinyproxy \
        tmux \
        unzip \
        util-linux \
        wget \
        xz-utils \
        zip \
    && rm -rf /var/lib/apt/lists/*

# VS Code Server. The official script picks the .deb for the architecture.
# Unpinned by default; pass --build-arg CODE_SERVER_VERSION=x.y.z to pin.
ARG CODE_SERVER_VERSION=
RUN if [ -n "$CODE_SERVER_VERSION" ]; then set -- --version "$CODE_SERVER_VERSION"; fi; \
    curl -fsSL https://code-server.dev/install.sh | sh -s -- "$@" \
    && rm -rf /root/.cache \
    && code-server --version

# The unprivileged user everything runs as. sudo asks for a password that only
# the host knows: the image ships the account locked, and the entrypoint sets
# the password aide generated for the namespace at every start. The one thing
# agent may do as root without it is the 9P mount its own tools need, through
# the wrappers below. No password is cached (timestamp_timeout=0), so a sudo
# you ran does not leave a window open for the agents.
# Default it to 1000 so bind-mounted
# workspaces line up with the usual first user on a Linux host; aide passes the
# host's uid/gid. The base image already ships an `ubuntu` user at 1000 (and on
# macOS gid 20 is `dialout`), so whatever holds the ids has to go first.
ARG AGENT_UID=1000
ARG AGENT_GID=1000
RUN set -eux; \
    if existing="$(getent passwd "$AGENT_UID" | cut -d: -f1)" && [ -n "$existing" ]; then \
        userdel --remove "$existing"; \
    fi; \
    if existing="$(getent group "$AGENT_GID" | cut -d: -f1)" && [ -n "$existing" ]; then \
        groupdel "$existing"; \
    fi; \
    groupadd --gid "$AGENT_GID" agent; \
    useradd --create-home --shell /bin/bash --uid "$AGENT_UID" --gid "$AGENT_GID" agent; \
    passwd --lock agent; \
    { \
        echo 'Defaults:agent timestamp_timeout=0'; \
        echo 'Defaults:agent env_keep += "http_proxy https_proxy no_proxy HTTP_PROXY HTTPS_PROXY NO_PROXY"'; \
        echo 'agent ALL=(ALL:ALL) ALL'; \
        echo 'agent ALL=(root) NOPASSWD: /usr/local/sbin/mount, /usr/local/sbin/umount'; \
    } > /etc/sudoers.d/agent; \
    chmod 0440 /etc/sudoers.d/agent; \
    visudo -cqf /etc/sudoers.d/agent; \
    mkdir -p /home/agent/workspace /home/agent/mnt /home/agent/.local/bin \
        /home/agent/.config /home/agent/.cache /var/cache/aide/xdg \
        /etc/aide /usr/local/lib/aide; \
    chown -R agent:agent /home/agent /var/cache/aide

# The runtime every stack's entrypoint.d hook builds on.
COPY --chmod=0755 stacks/base/files/entrypoint.sh stacks/base/files/lib.sh /etc/aide/
COPY --chmod=0755 stacks/base/files/install-node.sh /usr/local/lib/aide/
COPY --chmod=0755 stacks/base/files/aide-network.sh /usr/local/lib/aide/
COPY --chmod=0644 stacks/base/files/tinyproxy.conf /etc/aide/proxy/
# sudo resolves `mount` and `umount` through its secure_path, where
# /usr/local/sbin comes first, so `sudo mount` reaches these.
COPY --chmod=0755 stacks/base/files/aide-mount.sh /usr/local/sbin/mount
COPY --chmod=0755 stacks/base/files/aide-umount.sh /usr/local/sbin/umount

# /opt/node/current is linked by the common tail when a node stack is selected.
# Directories agent can write to go after the system ones, so nothing dropped
# there can stand in for a system command or for a tool the image ships.
# Caches go to the cache volume so they stay out of snapshots.
ENV PATH=$PATH:/opt/node/current/bin:/home/agent/.local/bin \
    XDG_CACHE_HOME=/var/cache/aide/xdg
USER root

# ---- stack: dotnet10 ----
# Runtime libraries the dotnet SDK needs on Ubuntu (ICU, OpenSSL, zlib, Kerberos,
# tzdata). Identical in dotnet8 and dotnet10 so selecting both is harmless.
RUN apt-get update \
    && apt-get install -y --no-install-recommends curl ca-certificates libicu74 libssl3t64 zlib1g libgssapi-krb5-2 tzdata \
    && rm -rf /var/lib/apt/lists/*

# Microsoft's dotnet-install.sh gives arch-neutral installs and lets several SDK
# channels coexist in one directory.
ARG DOTNET10_CHANNEL=10.0
RUN curl -fsSL https://dot.net/v1/dotnet-install.sh -o /tmp/dotnet-install.sh \
    && bash /tmp/dotnet-install.sh --channel "${DOTNET10_CHANNEL}" --install-dir /usr/share/dotnet --no-path \
    && rm -f /tmp/dotnet-install.sh \
    && ln -sf /usr/share/dotnet/dotnet /usr/local/bin/dotnet

# NUGET_PACKAGES points at the aide cache volume (cache: nuget); the opt-outs keep
# first-run banners, telemetry and dev-cert generation out of the container.
ENV DOTNET_ROOT=/usr/share/dotnet DOTNET_NOLOGO=1 DOTNET_CLI_TELEMETRY_OPTOUT=1 DOTNET_GENERATE_ASPNET_CERTIFICATE=false \
    DOTNET_RUNNING_IN_CONTAINER=true DOTNET_USE_POLLING_FILE_WATCHER=true \
    NUGET_PACKAGES=/var/cache/aide/nuget

# Fail the build early if the SDK did not install.
RUN dotnet --list-sdks
USER root

# ---- stack: python3 ----
# Python 3 from Ubuntu; pip downloads go to the cache volume so they survive container recreation.
RUN apt-get update \
 && apt-get install -y --no-install-recommends python3 python3-pip python3-venv python3-dev \
 && rm -rf /var/lib/apt/lists/*
ENV PIP_CACHE_DIR=/var/cache/aide/pip
USER root

# ---- stack: clang ----
# LLVM toolchain from Ubuntu noble, which resolves these packages to LLVM 18.
RUN apt-get update \
 && apt-get install -y --no-install-recommends clang lld lldb clangd clang-format \
 && rm -rf /var/lib/apt/lists/*
USER root

# ---- stack: golang ----
# Ubuntu's golang package lags far behind, so install the official tarball, checksum-verified
# against go.dev's own release metadata. GO_VERSION=latest tracks current stable.
ARG GO_VERSION=latest
ARG TARGETARCH
RUN set -eu; \
    json=$(curl -fsSL 'https://go.dev/dl/?mode=json'); \
    if [ "$GO_VERSION" = latest ]; then \
      ver=$(printf '%s' "$json" | jq -r '.[0].version'); \
    else \
      ver=go${GO_VERSION#go}; \
    fi; \
    file=$(printf '%s' "$json" | jq -r --arg v "$ver" --arg a "$TARGETARCH" \
      '.[] | select(.version==$v) | .files[] | select(.kind=="archive" and .os=="linux" and .arch==$a) | .filename' | head -n1); \
    sha=$(printf '%s' "$json" | jq -r --arg f "$file" '.[].files[] | select(.filename==$f) | .sha256' | head -n1); \
    [ -n "$file" ] && [ -n "$sha" ] || { echo "no linux/$TARGETARCH archive for $ver" >&2; exit 1; }; \
    curl -fsSL -o "/tmp/$file" "https://go.dev/dl/$file"; \
    echo "$sha  /tmp/$file" | sha256sum -c -; \
    tar -C /usr/local -xzf "/tmp/$file"; \
    rm -f "/tmp/$file"
# Caches live on the cache volume; -buildvcs=false because workspaces are often not git roots.
ENV PATH=/usr/local/go/bin:$PATH:/home/agent/go/bin \
    GOMODCACHE=/var/cache/aide/gomod \
    GOCACHE=/var/cache/aide/gobuild \
    GOFLAGS=-buildvcs=false
RUN go version
USER root

# ---- stack: node24 ----
# Installed under /opt/node/24 with versioned commands (node24, npm24, npx24);
# the highest installed Node stack becomes the default via /opt/node/current.
RUN /usr/local/lib/aide/install-node.sh 24
ENV npm_config_cache=/var/cache/aide/npm
USER root

# ---- stack: gh ----
# Official apt repo, so gh stays current with apt-get upgrade rather than Ubuntu's stale package.
RUN install -d -m 0755 /etc/apt/keyrings \
 && curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg -o /etc/apt/keyrings/githubcli-archive-keyring.gpg \
 && chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
 && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" > /etc/apt/sources.list.d/github-cli.list \
 && apt-get update \
 && apt-get install -y --no-install-recommends gh \
 && rm -rf /var/lib/apt/lists/*
# gh login (hosts.yml) must persist, so its config dir lives on the credentials volume.
ENV GH_CONFIG_DIR=/home/agent/.credentials/gh
USER root

# ---- stack: qode ----
# The installer hardcodes $HOME/.local/bin and needs no root, so run it as agent (the engine restores USER root after).
USER agent
RUN curl -sSfL https://raw.githubusercontent.com/nqode-io/qode/main/install.sh | sh
RUN /home/agent/.local/bin/qode --version
USER root

# ---- stack: terminalfs ----
# Release to install: latest or an exact vX.Y.Z. The upstream install script
# picks the self-contained linux x64/arm64 build.
ARG TERMINALFS_VERSION=v0.5.0
RUN curl -fsSL https://raw.githubusercontent.com/petar-stupar/terminalfs/main/scripts/install.sh \
        | sh -s -- --version "${TERMINALFS_VERSION}" --bin-dir /usr/local/bin \
    && terminalfs --version

# Each agent session gets its own 9P tree under $TERMINALFS_RUNTIME_DIR/terminalfs/<id>.
# terminalfs insists on an absolute, agent-owned, 0700 directory. Strict mode
# makes the Claude Code hook deny Bash that bypasses the tree; it is set here
# and again in the managed settings env so both the hook and any shell see it.
ENV TERMINALFS_RUNTIME_DIR=/home/agent/mnt/terminalfs-sessions \
    TERMINALFS_CLAUDE_STRICT=1
RUN install -d -o agent -g agent -m 0700 /home/agent/mnt/terminalfs-sessions

# The Claude Code marketplace dir is baked in, so registering the plugin at
# start (its state lives on the credentials volume) needs no network. It is
# written as root and stays root-owned: the managed policy names this path as
# the plugin's source, and agent must not be able to change what is installed
# from it.
RUN terminalfs plugin install claude --dir /usr/local/share/terminalfs/claude-code \
    && chmod -R go-w /usr/local/share/terminalfs \
    && test -d /usr/local/share/terminalfs/claude-code

USER agent

# The settings file is required at runtime; write the defaults into the image.
RUN terminalfs --init-settings \
    && test -s /home/agent/.config/terminalfs/settings.json
USER root

# ---- stack: claude ----
# Version for the official installer: stable, latest or an exact X.Y.Z.
ARG CLAUDE_VERSION=stable

# Everything Claude Code writes (credentials, .claude.json, session history,
# plugins) goes to the credentials volume, so a login survives a rebuild.
ENV CLAUDE_CONFIG_DIR=/home/agent/.credentials/claude

USER agent

# The installer its docs recommend; lands in ~/.local/bin (a symlink into
# ~/.local/share/claude/versions/).
RUN curl -fsSL https://claude.ai/install.sh | bash -s -- "${CLAUDE_VERSION}" \
    && ~/.local/bin/claude --version

# The VS Code extension, from Open VSX (code-server's marketplace).
RUN code-server --install-extension Anthropic.claude-code \
    && code-server --list-extensions | grep -qi '^anthropic.claude-code$'
USER root

# ---- stack: opencode-filesystem ----
# The 9P-filesystem build of opencode, from the fork's rolling prerelease.
ARG OPENCODE_FS_REPO=petar-stupar/opencode
ARG OPENCODE_FS_TAG=filesystem-latest
RUN set -eux; \
    case "$TARGETARCH" in \
        amd64) asset=opencode-linux-x64.tar.gz ;; \
        arm64) asset=opencode-linux-arm64.tar.gz ;; \
        *) echo "unsupported architecture: $TARGETARCH" >&2; exit 1 ;; \
    esac; \
    curl -fsSL -o /tmp/opencode.tar.gz \
        "https://github.com/${OPENCODE_FS_REPO}/releases/download/${OPENCODE_FS_TAG}/${asset}"; \
    mkdir -p /tmp/opencode /opt/opencode-fs; \
    tar -xzf /tmp/opencode.tar.gz -C /tmp/opencode; \
    install -m 0755 "$(find /tmp/opencode -type f -path '*/bin/opencode' | head -1)" /opt/opencode-fs/opencode; \
    rm -rf /tmp/opencode /tmp/opencode.tar.gz
ENV PATH=/opt/opencode-fs:$PATH
RUN opencode --version

USER agent

# opencode keeps its credentials (SQLite) in $XDG_DATA_HOME/opencode. Link just
# that directory to the credentials volume; moving XDG_DATA_HOME wholesale would
# drag code-server's extensions along.
RUN mkdir -p ~/.credentials/opencode ~/.local/share \
    && ln -sfn /home/agent/.credentials/opencode /home/agent/.local/share/opencode
USER root

# ---- stack: dotnetdocfs ----
# Release to install: latest or an exact vX.Y.Z. The upstream install script
# picks the self-contained linux x64/arm64 build of `dotnetdoc`.
ARG DOTNETDOCFS_VERSION=latest
RUN curl -fsSL https://raw.githubusercontent.com/petar-stupar/dotnetdocfs/main/scripts/install.sh \
        | sh -s -- --version "${DOTNETDOCFS_VERSION}" --bin-dir /usr/local/bin \
    && dotnetdoc --version

# The mountpoint must exist and belong to agent, who runs the server and mounts
# it (through the mount wrapper sudo allows it) at start. The port is loopback-only.
RUN install -d -o agent -g agent /home/agent/mnt/dotnetdocfs
ENV DOTNETDOCFS_PORT=15640
USER root

# ---- aide common tail ----
RUN if [ -d /opt/node ]; then v=$(ls /opt/node | grep -E '^[0-9]+$' | sort -n | tail -1); [ -n "$v" ] && ln -sfn /opt/node/$v /opt/node/current; fi
RUN install -d -m 0755 /etc/claude-code
COPY --chmod=0644 aide/managed-settings.json /etc/claude-code/managed-settings.json
COPY --chown=agent:agent aide/opencode.json /home/agent/.config/opencode/opencode.json
COPY aide/stacks aide/cache-dirs aide/allow-hosts /etc/aide/
COPY --chmod=0755 aide/entrypoint.d/ /etc/aide/entrypoint.d/
ENV AIDE_STACKS="base dotnet10 python3 clang golang node24 gh qode terminalfs claude opencode-filesystem dotnetdocfs" WORKSPACE=/home/agent/workspace CODE_SERVER_PORT=8080
USER root
WORKDIR /home/agent/workspace
EXPOSE 8080
ENTRYPOINT ["/etc/aide/entrypoint.sh"]
