# syntax=docker/dockerfile:1
# Generated by aide. Stacks: base opencode
FROM ubuntu:24.04
ARG TARGETARCH
ENV DEBIAN_FRONTEND=noninteractive LANG=C.UTF-8

# ---- stack: base ----
# mount/mountpoint (util-linux) mount the 9P filesystems and setpriv drops
# privileges in the entrypoint. tinyproxy and iptables are the network
# allowlist (aide-network.sh), and netcat-openbsd carries ssh through it. ripgrep is used by both agents' search tools;
# without a system rg they each download their own copy on first use. xz-utils
# unpacks the nodejs.org tarballs.
RUN apt-get update && apt-get install -y --no-install-recommends \
        bash \
        build-essential \
        ca-certificates \
        curl \
        file \
        git \
        gnupg \
        gzip \
        htop \
        iptables \
        jq \
        less \
        libsecret-1-0 \
        locales \
        mount \
        nano \
        neovim \
        netcat-openbsd \
        openssh-client \
        pkg-config \
        procps \
        ripgrep \
        rsync \
        sudo \
        tar \
        tinyproxy \
        tmux \
        unzip \
        util-linux \
        wget \
        xz-utils \
        zip \
    && rm -rf /var/lib/apt/lists/*

# VS Code Server. The official script picks the .deb for the architecture.
# Unpinned by default; pass --build-arg CODE_SERVER_VERSION=x.y.z to pin.
ARG CODE_SERVER_VERSION=
RUN if [ -n "$CODE_SERVER_VERSION" ]; then set -- --version "$CODE_SERVER_VERSION"; fi; \
    curl -fsSL https://code-server.dev/install.sh | sh -s -- "$@" \
    && rm -rf /root/.cache \
    && code-server --version

# The unprivileged user everything runs as. sudo asks for a password that only
# the host knows: the image ships the account locked, and the entrypoint sets
# the password aide generated for the namespace at every start. The one thing
# agent may do as root without it is the 9P mount its own tools need, through
# the wrappers below. No password is cached (timestamp_timeout=0), so a sudo
# you ran does not leave a window open for the agents.
# Default it to 1000 so bind-mounted
# workspaces line up with the usual first user on a Linux host; aide passes the
# host's uid/gid. The base image already ships an `ubuntu` user at 1000 (and on
# macOS gid 20 is `dialout`), so whatever holds the ids has to go first.
ARG AGENT_UID=1000
ARG AGENT_GID=1000
RUN set -eux; \
    if existing="$(getent passwd "$AGENT_UID" | cut -d: -f1)" && [ -n "$existing" ]; then \
        userdel --remove "$existing"; \
    fi; \
    if existing="$(getent group "$AGENT_GID" | cut -d: -f1)" && [ -n "$existing" ]; then \
        groupdel "$existing"; \
    fi; \
    groupadd --gid "$AGENT_GID" agent; \
    useradd --create-home --shell /bin/bash --uid "$AGENT_UID" --gid "$AGENT_GID" agent; \
    passwd --lock agent; \
    { \
        echo 'Defaults:agent timestamp_timeout=0'; \
        echo 'Defaults:agent env_keep += "http_proxy https_proxy no_proxy HTTP_PROXY HTTPS_PROXY NO_PROXY"'; \
        echo 'agent ALL=(ALL:ALL) ALL'; \
        echo 'agent ALL=(root) NOPASSWD: /usr/local/sbin/mount, /usr/local/sbin/umount'; \
    } > /etc/sudoers.d/agent; \
    chmod 0440 /etc/sudoers.d/agent; \
    visudo -cqf /etc/sudoers.d/agent; \
    mkdir -p /home/agent/workspace /home/agent/mnt /home/agent/.local/bin \
        /home/agent/.config /home/agent/.cache /var/cache/aide/xdg \
        /etc/aide /usr/local/lib/aide; \
    chown -R agent:agent /home/agent /var/cache/aide

# The runtime every stack's entrypoint.d hook builds on.
COPY --chmod=0755 stacks/base/files/entrypoint.sh stacks/base/files/lib.sh /etc/aide/
COPY --chmod=0755 stacks/base/files/install-node.sh /usr/local/lib/aide/
COPY --chmod=0755 stacks/base/files/aide-network.sh /usr/local/lib/aide/
COPY --chmod=0644 stacks/base/files/tinyproxy.conf /etc/aide/proxy/
# sudo resolves `mount` and `umount` through its secure_path, where
# /usr/local/sbin comes first, so `sudo mount` reaches these.
COPY --chmod=0755 stacks/base/files/aide-mount.sh /usr/local/sbin/mount
COPY --chmod=0755 stacks/base/files/aide-umount.sh /usr/local/sbin/umount

# /opt/node/current is linked by the common tail when a node stack is selected.
# Directories agent can write to go after the system ones, so nothing dropped
# there can stand in for a system command or for a tool the image ships.
# Caches go to the cache volume so they stay out of snapshots.
ENV PATH=$PATH:/opt/node/current/bin:/home/agent/.local/bin \
    XDG_CACHE_HOME=/var/cache/aide/xdg
USER root

# ---- stack: opencode ----
# Empty installs the latest release; otherwise an exact version.
ARG OPENCODE_VERSION=

USER agent

# The upstream installer always installs into ~/.opencode/bin.
RUN if [ -n "${OPENCODE_VERSION}" ]; then \
        curl -fsSL https://opencode.ai/install | bash -s -- --no-modify-path --version "${OPENCODE_VERSION}"; \
    else \
        curl -fsSL https://opencode.ai/install | bash -s -- --no-modify-path; \
    fi
ENV PATH=$PATH:/home/agent/.opencode/bin

# opencode keeps its credentials (SQLite) in $XDG_DATA_HOME/opencode. Link just
# that directory to the credentials volume; moving XDG_DATA_HOME wholesale would
# drag code-server's extensions along.
RUN mkdir -p ~/.credentials/opencode ~/.local/share \
    && ln -sfn /home/agent/.credentials/opencode /home/agent/.local/share/opencode

RUN opencode --version
USER root

# ---- aide common tail ----
RUN if [ -d /opt/node ]; then v=$(ls /opt/node | grep -E '^[0-9]+$' | sort -n | tail -1); [ -n "$v" ] && ln -sfn /opt/node/$v /opt/node/current; fi
COPY --chown=agent:agent aide/opencode.json /home/agent/.config/opencode/opencode.json
COPY aide/stacks aide/cache-dirs aide/allow-hosts /etc/aide/
COPY --chmod=0755 aide/entrypoint.d/ /etc/aide/entrypoint.d/
ENV AIDE_STACKS="base opencode" WORKSPACE=/home/agent/workspace CODE_SERVER_PORT=8080
USER root
WORKDIR /home/agent/workspace
EXPOSE 8080
ENTRYPOINT ["/etc/aide/entrypoint.sh"]
